"""Script to check Twilio configuration and test webhook connectivity."""
import asyncio
import sys
from app.config import settings
from app.database import get_collection

def check_twilio_config():
    """Check Twilio configuration from environment."""
    print("=" * 60)
    print("TWILIO CONFIGURATION CHECK")
    print("=" * 60)
    
    # Check Account SID
    if settings.twilio_account_sid:
        print(f"✓ TWILIO_ACCOUNT_SID: {settings.twilio_account_sid[:10]}...{settings.twilio_account_sid[-4:]}")
    else:
        print("✗ TWILIO_ACCOUNT_SID: NOT SET")
    
    # Check Auth Token
    if settings.twilio_auth_token:
        masked_token = settings.twilio_auth_token[:4] + "..." + settings.twilio_auth_token[-4:] if len(settings.twilio_auth_token) > 8 else "***"
        print(f"✓ TWILIO_AUTH_TOKEN: {masked_token} (SET)")
        print("  ⚠️  Signature validation is ENABLED")
        print("  ⚠️  Manual testing (FastAPI docs/curl) will fail without X-Twilio-Signature header")
    else:
        print("✗ TWILIO_AUTH_TOKEN: NOT SET")
        print("  ✓ Signature validation is DISABLED (dev mode)")
        print("  ✓ Manual testing will work")
    
    # Check Phone Number
    if settings.twilio_phone_number:
        print(f"✓ TWILIO_PHONE_NUMBER: {settings.twilio_phone_number}")
    else:
        print("✗ TWILIO_PHONE_NUMBER: NOT SET")
    
    # Check WhatsApp From
    if settings.twilio_whatsapp_from:
        print(f"✓ TWILIO_WHATSAPP_FROM: {settings.twilio_whatsapp_from}")
    else:
        print("✗ TWILIO_WHATSAPP_FROM: NOT SET")
    
    print("\n" + "=" * 60)
    print("SIGNATURE VALIDATION STATUS")
    print("=" * 60)
    
    if settings.twilio_auth_token:
        print("⚠️  SIGNATURE VALIDATION: ENABLED")
        print("\nThis means:")
        print("  • Real Twilio webhooks will be validated ✓")
        print("  • Manual testing (FastAPI docs/curl) will FAIL ✗")
        print("  • To test manually, temporarily unset TWILIO_AUTH_TOKEN")
        print("\nFor production:")
        print("  • Keep TWILIO_AUTH_TOKEN set for security")
        print("  • Use Twilio's webhook testing tools or ngrok for testing")
    else:
        print("✓ SIGNATURE VALIDATION: DISABLED (dev mode)")
        print("\nThis means:")
        print("  • Manual testing will work ✓")
        print("  • Real Twilio webhooks will NOT be validated ✗")
        print("  • Set TWILIO_AUTH_TOKEN for production security")
    
    print("\n" + "=" * 60)
    print("WEBHOOK ENDPOINT")
    print("=" * 60)
    print(f"Endpoint: POST /twilio/webhook")
    print(f"Full URL: http://127.0.0.1:8000/twilio/webhook")
    print("\nRequired Headers (when TWILIO_AUTH_TOKEN is set):")
    print("  • X-Twilio-Signature: [Generated by Twilio]")
    print("\nRequired Form Data:")
    print("  • From: Phone number (e.g., +19392664227)")
    print("  • Body: Message content (e.g., 'confirm' or 'cancel')")
    print("  • MessageSid: [Optional]")
    print("  • AccountSid: [Optional]")
    
    return {
        "account_sid_set": bool(settings.twilio_account_sid),
        "auth_token_set": bool(settings.twilio_auth_token),
        "phone_set": bool(settings.twilio_phone_number),
        "validation_enabled": bool(settings.twilio_auth_token)
    }


async def check_volunteers_in_db():
    """Check if there are volunteers in the database with phone numbers."""
    print("\n" + "=" * 60)
    print("VOLUNTEER DATABASE CHECK")
    print("=" * 60)
    
    try:
        volunteers_collection = get_collection("volunteers")
        count = await volunteers_collection.count_documents({})
        print(f"Total volunteers in database: {count}")
        
        if count > 0:
            print("\nSample volunteers (first 5):")
            cursor = volunteers_collection.find({}, {"name": 1, "phone": 1, "email": 1}).limit(5)
            async for vol in cursor:
                name = vol.get("name", "N/A")
                phone = vol.get("phone", "N/A")
                print(f"  • {name}: {phone}")
        else:
            print("⚠️  No volunteers found in database!")
            print("  Run: python seed_from_csv.py to seed volunteers")
        
        return count > 0
    except Exception as e:
        print(f"✗ Error checking volunteers: {e}")
        return False


async def check_assignments_in_db():
    """Check if there are active assignments in the database."""
    print("\n" + "=" * 60)
    print("ASSIGNMENTS DATABASE CHECK")
    print("=" * 60)
    
    try:
        assignments_collection = get_collection("assignments")
        total = await assignments_collection.count_documents({})
        active = await assignments_collection.count_documents({"status": {"$in": ["assigned", "backup"]}})
        
        print(f"Total assignments: {total}")
        print(f"Active assignments (assigned/backup): {active}")
        
        if active > 0:
            print("\nSample active assignments (first 3):")
            cursor = assignments_collection.find(
                {"status": {"$in": ["assigned", "backup"]}},
                {"volunteer_id": 1, "camp_id": 1, "status": 1}
            ).limit(3)
            async for assignment in cursor:
                print(f"  • Assignment ID: {assignment.get('_id')}")
                print(f"    Volunteer ID: {assignment.get('volunteer_id')}")
                print(f"    Status: {assignment.get('status')}")
        else:
            print("⚠️  No active assignments found!")
            print("  Run: python demo_agent_run.py to create assignments")
        
        return active > 0
    except Exception as e:
        print(f"✗ Error checking assignments: {e}")
        return False


async def main():
    """Run all checks."""
    config = check_twilio_config()
    has_volunteers = await check_volunteers_in_db()
    has_assignments = await check_assignments_in_db()
    
    print("\n" + "=" * 60)
    print("SUMMARY & RECOMMENDATIONS")
    print("=" * 60)
    
    if not config["auth_token_set"]:
        print("\n⚠️  For testing the webhook manually:")
        print("   Current setup allows manual testing (validation disabled)")
        print("   You can test via FastAPI docs or curl")
    else:
        print("\n⚠️  For testing the webhook manually:")
        print("   Option 1: Temporarily disable validation")
        print("     - Comment out or remove TWILIO_AUTH_TOKEN from .env")
        print("     - Restart the server")
        print("     - Test manually")
        print("     - Re-enable for production")
        print("\n   Option 2: Use Twilio's webhook testing tools")
        print("     - Use ngrok to expose your local server")
        print("     - Configure Twilio webhook URL to ngrok URL")
        print("     - Send test messages from Twilio")
        print("\n   Option 3: Create a test endpoint (bypasses validation)")
        print("     - Add a /twilio/webhook/test endpoint for development")
    
    if not has_volunteers:
        print("\n⚠️  No volunteers in database - webhook won't find volunteers")
    
    if not has_assignments:
        print("\n⚠️  No active assignments - webhook will return 'no active assignments'")
    
    print("\n" + "=" * 60)


if __name__ == "__main__":
    asyncio.run(main())

